### ISSUE TITLE
getInitialState: () => null causes failures

### ISSUE THREAD

**Issue by appsforartists** [optimizely/nuclear-js#37] opened 2015-05-05 23:24 UTC
Steps to reproduce:

1) Return `null` from a Store's `getInitialState`.
2) Dispatch an action that the store doesn't handle.

Expected result:

The store ignores the action.

Actual result:

`Store handler must return a value, did you forget a return statement`

**Comment by jordangarcia** [comment] 2015-05-09 19:49
@appsforartists not able to replicate this issue exactly

I was able to replicate it if I made `getInitialState` return undefined.  But it seems to work when passed `null`

**Comment by bhamodi** [comment] 2015-05-11 17:49
@appsforartists, we are unable to reproduce this, so I'll close this issue for now.
Please feel free to re-open if you encounter this issue again with the latest version of NuclearJS.

**Closed by bhamodi** 2015-05-11 17:49 UTC
Labels: invalid

**Comment by rattrayalex** [comment] 2015-06-29 06:45
I am getting this as well on 1.0.5

**Comment by rattrayalex** [comment] 2015-06-29 06:46
I'm quite mystified as to why, as I'm not returning null or undefined anywhere, and I believe I'm handling all the actions I'm dispatching...

**Comment by rattrayalex** [comment] 2015-06-29 07:08
The problem has been mysteriously resolved =) 

However, `console.log` doesn't appear to be working in my store handlers... 
 
```js
var l = console.log.bind(console)

export default Nuclear.Store({
  getInitialState() {
    return Immutable.Set()
  }
  initialize() {
    console.log('1')
    l('2')
    this.on(ACTION, (current, { thing }) => {
      console.log('3')
      l('4')
      return toImmutable(thing)
   })
  }
})

// prints: 
// 1
// 2
// Dispatch: ACTION
// (new state is updated - the handler func actually ran)
```

I think this might be some kind of strange scoping issue unrelated to Nuclear... but thought it might be related/helpful to others who hit this error, so I posted here.

**Comment by jordangarcia** [comment] 2015-06-29 07:10
Hey Alex

This is actually due to the use of console.group for dispatches

your console messages are within the collapsed group

**Comment by rattrayalex** [comment] 2015-06-29 07:30
... so they are. Not sure how I missed that. Thanks @jordangarcia .

**Comment by MatthiasWinkelmann** [comment] 2015-11-14 03:48
I 'successfully' managed to reproduce this by specifying a data binding to `undefined`.

Example:

<code>
  getDataBindings() {
    return {
      stuff: undefined
    }
}
</code>
